from .callbacks import PlotSpectogramCallback
from .contrastive_learning import ContrastiveLearning
from .linear_evaluation import LinearEvaluation
from .supervised_learning import SupervisedLearning
